repos:
-   repo: https://github.com/tekwizely/pre-commit-golang
    rev: v1.0.0-rc.1
    hooks:
    -   id: go-build-mod
    -   id: go-mod-tidy-repo
    -   id: go-test-mod
    -   id: go-fumpt-repo
    -   id: golangci-lint-mod
